apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1-springboot
  template:
    metadata:
      labels:
        app: app1-springboot
    spec:
      containers:
        - name: springboot
          image: kulshresthaaayush10/app1-docker-demo:app1-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: app1-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app1-springboot
